apiVersion: v1
kind: Service
metadata:
  name: mysql-external
  namespace: demo
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      # K8s NodePort 默认范围：30000-32767
      # 你可以按需改，但要确保不和集群其它 NodePort 冲突
      nodePort: 30306

